SelectionTool:
    name: '&bSelection Tool'
    type: 'STONE_HOE'
    lore:
        - ''
        - '&dUse to select gateway bounds'
        - ''
        - '&7Right-click to set positions'

# Amount of time a portal is open (Default: 1 minute)
default-open-time: 1

# Debugging Settings
debug: false